# Custom Nginx Dockerfile 
FROM nginx 

COPY ./default.conf /etc/nginx/conf.d/default.conf 

# Expose port 80
EXPOSE 85

# Command untuk menjalankan nginx 
CMD ["nginx", "-g", "daemon off;"]

#this is Dockerfile.nginx